#!/bin/bash


#2. Run the BWASP workflow, all replicate instances simultaneously but
#   with staggered start time to avoid overload from multiple bowtie2
#   instances
#
#2.1 EmergingQueen samples:
#
echo "Analyzing EmergingQueen samples ..."
cd Emerging/EmergingQueen/replicate1
date
echo " starting on replicate1 ..."
time make -j 4 -f Makefile_WF1-6se_EQ1 >& errcheck &
sleep 3s
cd ../replicate2
date
echo " starting on replicate2 ..."
time make -j 4 -f Makefile_WF1-6se_EQ2 >& errcheck &
sleep 3s
cd ../replicate3
date
echo " starting on replicate3 ..."
time make -j 4 -f Makefile_WF1-6se_EQ3 >& errcheck &
sleep 3s
cd ../replicate4
date
echo " starting on replicate4 ..."
time make -j 4 -f Makefile_WF1-6se_EQ4 >& errcheck &
sleep 3s
cd ../replicate5
date
echo " starting on replicate5 ..."
time make -j 4 -f Makefile_WF1-6se_EQ5 >& errcheck &
sleep 3s
cd ../replicate6
date
echo " starting on replicate6 ..."
time make -j 4 -f Makefile_WF1-6se_EQ6 >& errcheck &
cd ../../..
wait
echo "  done with EmergingQueen replicates ..."
date

# 2.11: merge the EmergingQueen data:
#
cd Emerging/EmergingQueen
time make -j 6 -f Makefile_merge_EQ >& errcheck &
cd ../..
wait
echo "  done with EmergingQueen merge ..."
date


#2.2 EmergingWorker samples:
#
echo "Analyzing EmergingWorker samples ..."
cd Emerging/EmergingWorker/replicate1
date
echo " starting on replicate1 ..."
time make -j 4 -f Makefile_WF1-6se_EW1 >& errcheck &
sleep 3s
cd ../replicate2
date
echo " starting on replicate2 ..."
time make -j 4 -f Makefile_WF1-6se_EW2 >& errcheck &
sleep 3s
cd ../replicate3
date
echo " starting on replicate3 ..."
time make -j 4 -f Makefile_WF1-6se_EW3 >& errcheck &
sleep 3s
cd ../replicate4
date
echo " starting on replicate4 ..."
time make -j 4 -f Makefile_WF1-6se_EW4 >& errcheck &
sleep 3s
cd ../replicate5
date
echo " starting on replicate5 ..."
time make -j 4 -f Makefile_WF1-6se_EW5 >& errcheck &
sleep 3s
cd ../replicate6
date
echo " starting on replicate6 ..."
time make -j 4 -f Makefile_WF1-6se_EW6 >& errcheck &
cd ../../..
wait
echo "  done with EmergingWorker replicates ..."
date

# 2.21: merge the EmergingWorker data:
#
cd Emerging/EmergingWorker
time make -j 6 -f Makefile_merge_EW >& errcheck &
cd ../..
wait
echo "  done with EmergingWorker merge ..."
date


#2.3 OldQueen samples:
#
echo "Analyzing OldQueen samples ..."
cd Old/OldQueen/replicate1
date
echo " starting on replicate1 ..."
time make -j 4 -f Makefile_WF1-6se_OQ1 >& errcheck &
sleep 3s
cd ../replicate2
date
echo " starting on replicate2 ..."
time make -j 4 -f Makefile_WF1-6se_OQ2 >& errcheck &
sleep 3s
cd ../replicate3
date
echo " starting on replicate3 ..."
time make -j 4 -f Makefile_WF1-6se_OQ3 >& errcheck &
sleep 3s
cd ../replicate4
date
echo " starting on replicate4 ..."
time make -j 4 -f Makefile_WF1-6se_OQ4 >& errcheck &
sleep 3s
cd ../replicate5
date
echo " starting on replicate5 ..."
time make -j 4 -f Makefile_WF1-6se_OQ5 >& errcheck &
cd ../../..
wait
echo "  done with OldQueen replicates ..."
date

# 2.31: merge the OldQueen data:
#
cd Old/OldQueen
time make -j 6 -f Makefile_merge_OQ >& errcheck &
cd ../..
wait
echo "  done with OldQueen merge ..."
date


#2.4 OldWorker samples:
#
echo "Analyzing OldWorker samples ..."
cd Old/OldWorker/replicate1
date
echo " starting on replicate1 ..."
time make -j 4 -f Makefile_WF1-6se_OW1 >& errcheck &
sleep 3s
cd ../replicate2
date
echo " starting on replicate2 ..."
time make -j 4 -f Makefile_WF1-6se_OW2 >& errcheck &
sleep 3s
cd ../replicate3
date
echo " starting on replicate3 ..."
time make -j 4 -f Makefile_WF1-6se_OW3 >& errcheck &
sleep 3s
cd ../replicate4
date
echo " starting on replicate4 ..."
time make -j 4 -f Makefile_WF1-6se_OW4 >& errcheck &
sleep 3s
cd ../replicate5
date
echo " starting on replicate5 ..."
time make -j 4 -f Makefile_WF1-6se_OW5 >& errcheck &
sleep 3s
cd ../replicate6
date
echo " starting on replicate6 ..."
time make -j 4 -f Makefile_WF1-6se_OW6 >& errcheck &
sleep 3s
cd ../replicate7
date
echo " starting on replicate7 ..."
time make -j 4 -f Makefile_WF1-6se_OW7 >& errcheck &
cd ../../..
wait
echo "  done with OldWorker replicates ..."
date

# 2.41: merge the OldWorker data:
#
cd Old/OldWorker
time make -j 6 -f Makefile_merge_OW >& errcheck &
cd ../..
wait
echo "  done with OldWorker merge ..."
date


