#!/bin/bash

cd Emerging/EmergingQueen/replicate1/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Emerging/EmergingQueen/replicate2/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Emerging/EmergingQueen/replicate3/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Emerging/EmergingQueen/replicate4/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Emerging/EmergingQueen/replicate5/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Emerging/EmergingQueen/replicate6/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Emerging/EmergingQueen/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../

cd Emerging/EmergingWorker/replicate1/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Emerging/EmergingWorker/replicate2/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Emerging/EmergingWorker/replicate3/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Emerging/EmergingWorker/replicate4/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Emerging/EmergingWorker/replicate5/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Emerging/EmergingWorker/replicate6/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Emerging/EmergingWorker/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../

cd Old/OldQueen/replicate1/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Old/OldQueen/replicate2/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Old/OldQueen/replicate3/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Old/OldQueen/replicate4/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Old/OldQueen/replicate5/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Old/OldQueen/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../

cd Old/OldWorker/replicate1/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Old/OldWorker/replicate2/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Old/OldWorker/replicate3/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Old/OldWorker/replicate4/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Old/OldWorker/replicate5/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Old/OldWorker/replicate6/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Old/OldWorker/replicate7/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Old/OldWorker/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../
