#!/bin/bash

cd New/NewQueen/replicate1/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd New/NewQueen/replicate2/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd New/NewQueen/replicate3/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd New/NewQueen/replicate4/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd New/NewQueen/replicate5/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd New/NewQueen/replicate6/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd New/NewQueen/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../

cd New/NewWorker/replicate1/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd New/NewWorker/replicate2/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd New/NewWorker/replicate3/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd New/NewWorker/replicate4/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd New/NewWorker/replicate5/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd New/NewWorker/replicate6/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd New/NewWorker/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../

cd Old/OldQueen/replicate1/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Old/OldQueen/replicate2/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Old/OldQueen/replicate3/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Old/OldQueen/replicate4/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Old/OldQueen/replicate5/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Old/OldQueen/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../

cd Old/OldWorker/replicate1/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Old/OldWorker/replicate2/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Old/OldWorker/replicate3/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Old/OldWorker/replicate4/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Old/OldWorker/replicate5/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Old/OldWorker/replicate6/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Old/OldWorker/replicate7/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../../
cd Old/OldWorker/; make -f Makefile* cleanup; make -f Makefile* finishup; cd ../../
