#!/bin/bash
mkdir NGS_DIR
cd NGS_DIR


#ABYSS
	apt-get install abyss

#Discovar
	mkdir Discovar
	cd Discovar/
	wget ftp://ftp.broadinstitute.org/pub/crd/Discovar/latest_source_code/LATEST_VERSION.tar.gz 
	tar -xzf LATEST_VERSION.tar.gz 
	cd discovar-52488/
	./configure
	make all
#This version of Discovar does NOT compile on Ubuntu 16.04.
#It does compile on Ubuntu 14.04, and thus for now our approach is to compile
#on an instance of Ubuntu 14.04, and then copy the Discovar binary to
#/usr/local/bin here.
#	make install
	make clean
	cd ../..

#DiscovarDeNovo
	mkdir DiscovarDeNovo
	cd DiscovarDeNovo/
	wget ftp://ftp.broadinstitute.org/pub/crd/DiscovarDeNovo/latest_source_code/LATEST_VERSION.tar.gz 
	tar -xzf LATEST_VERSION.tar.gz 
	cd discovardenovo-52488/
	./configure
	make all
#This version of DiscovarDeNovo does NOT compile on Ubuntu 16.04.
#It does compile on Ubuntu 14.04, and thus for now our approach is to compile
#on an instance of Ubuntu 14.04, and then copy the DiscovarDeNovo binary to
#/usr/local/bin here.
#	make install
	make clean
	cd ../..

#Picard
	mkdir Picard
	cd Picard
	wget https://github.com/broadinstitute/picard/releases/download/2.10.9/picard.jar
	cd ..

#SRAssembler
	git clone https://github.com/BrendelGroup/SRAssembler
	cd SRAssembler/
	cd src
	make
	make clean
	make mpi
	make clean
	make install
	cd ../..
