#!/bin/bash

cp FeDATA/Fexs.gdna.fa   MCALLS/Fe/genome/
cp FeDATA/Fexs.gff3      MCALLS/Fe/genome/

cp FeDATA/EQ1_trimmed.fq   MCALLS/Fe/Emerging/EmergingQueen/replicate1/EQ1_trimmed.fq
cp FeDATA/EQ2_trimmed.fq   MCALLS/Fe/Emerging/EmergingQueen/replicate2/EQ2_trimmed.fq
cp FeDATA/EQ3_trimmed.fq   MCALLS/Fe/Emerging/EmergingQueen/replicate3/EQ3_trimmed.fq
cp FeDATA/EQ4_trimmed.fq   MCALLS/Fe/Emerging/EmergingQueen/replicate4/EQ4_trimmed.fq
cp FeDATA/EQ5_trimmed.fq   MCALLS/Fe/Emerging/EmergingQueen/replicate5/EQ5_trimmed.fq
cp FeDATA/EQ6_trimmed.fq   MCALLS/Fe/Emerging/EmergingQueen/replicate6/EQ6_trimmed.fq
cp FeDATA/EW1_trimmed.fq   MCALLS/Fe/Emerging/EmergingWorker/replicate1/EW1_trimmed.fq
cp FeDATA/EW2_trimmed.fq   MCALLS/Fe/Emerging/EmergingWorker/replicate2/EW2_trimmed.fq
cp FeDATA/EW3_trimmed.fq   MCALLS/Fe/Emerging/EmergingWorker/replicate3/EW3_trimmed.fq
cp FeDATA/EW4_trimmed.fq   MCALLS/Fe/Emerging/EmergingWorker/replicate4/EW4_trimmed.fq
cp FeDATA/EW5_trimmed.fq   MCALLS/Fe/Emerging/EmergingWorker/replicate5/EW5_trimmed.fq
cp FeDATA/EW6_trimmed.fq   MCALLS/Fe/Emerging/EmergingWorker/replicate6/EW6_trimmed.fq
cp FeDATA/OQ1_trimmed.fq   MCALLS/Fe/Old/OldQueen/replicate1/OQ1_trimmed.fq
cp FeDATA/OQ2_trimmed.fq   MCALLS/Fe/Old/OldQueen/replicate2/OQ2_trimmed.fq
cp FeDATA/OQ3_trimmed.fq   MCALLS/Fe/Old/OldQueen/replicate3/OQ3_trimmed.fq
cp FeDATA/OQ4_trimmed.fq   MCALLS/Fe/Old/OldQueen/replicate4/OQ4_trimmed.fq
cp FeDATA/OQ5_trimmed.fq   MCALLS/Fe/Old/OldQueen/replicate5/OQ5_trimmed.fq
cp FeDATA/OW1_trimmed.fq   MCALLS/Fe/Old/OldWorker/replicate1/OW1_trimmed.fq
cp FeDATA/OW2_trimmed.fq   MCALLS/Fe/Old/OldWorker/replicate2/OW2_trimmed.fq
cp FeDATA/OW3_trimmed.fq   MCALLS/Fe/Old/OldWorker/replicate3/OW3_trimmed.fq
cp FeDATA/OW4_trimmed.fq   MCALLS/Fe/Old/OldWorker/replicate4/OW4_trimmed.fq
cp FeDATA/OW5_trimmed.fq   MCALLS/Fe/Old/OldWorker/replicate5/OW5_trimmed.fq
cp FeDATA/OW6_trimmed.fq   MCALLS/Fe/Old/OldWorker/replicate6/OW6_trimmed.fq
cp FeDATA/OW7_trimmed.fq   MCALLS/Fe/Old/OldWorker/replicate7/OW7_trimmed.fq
